# Generated by Django 5.1.6 on 2025-03-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img', models.ImageField(blank=True, default='', upload_to='brands')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disable', 'Disable')], max_length=100)),
            ],
        ),
    ]
