# Generated by Django 5.1.6 on 2025-03-09 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('mrp', models.CharField(max_length=255)),
                ('discount', models.IntegerField()),
                ('code', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, default='', upload_to='Products')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disable', 'Disable')], max_length=100, null=True)),
                ('stock', models.CharField(max_length=100)),
                ('trendingstatus', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=255)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery.category')),
            ],
        ),
    ]
