# Generated by Django 5.1.6 on 2025-03-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='Category'),
        ),
    ]
