# Generated by Django 5.1.6 on 2025-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
