# Generated by Django 5.1.6 on 2025-03-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0010_order_qty_alter_order_status_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
